[package]
name = "retto-cli"
version.workspace = true
edition.workspace = true

[dependencies]
retto-core = { path = "../retto-core" }
walkdir.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true