name: Check and Build retto

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: write

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4
      - name: Setup Rust toolchain
        run: just setup
      - name: Check formatting
        run: just fmt-check

  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4
      - name: Setup Rust toolchain
        run: just setup
      - name: Check Clippy
        run: just clippy-check

  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4
      - name: Setup Rust toolchain
        run: just setup
      - name: Check Clippy
        run: just build-check

  build-cli:
    name: Build retto-cli
    runs-on: ${{ matrix.host }}
    needs: [ "fmt-check", "clippy-check", "build-check" ]
    strategy:
      matrix:
        host: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4
      - name: Setup Rust toolchain
        run: just setup
      - name: Build retto-cli
        run: |
          just build-cli
          cd target/release; ls
          ls -la

  build-wasm:
    name: Build retto-wasm
    runs-on: ubuntu-latest
    needs: [ "fmt-check", "clippy-check", "build-check" ]
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          package_json_file: "retto-wasm/fe/package.json"
      - name: Setup Rust toolchain
        run: just setup
      - name: Build retto-wasm
        run: just build-wasm
