name: Build and Publish retto

on:
  workflow_run:
    workflows: [Check retto]
    types:
      - completed

permissions:
  actions: write

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-cli:
    name: Build retto-cli
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        host: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4
      - name: Setup Rust toolchain
        run: just setup
      - name: Build retto-cli
        run: |
          just build-cli
          ls

  build-wasm:
    name: Build retto-wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4
      - name: Setup Rust toolchain
        run: just setup
      - name: Build retto-wasm
        run: just build-wasm
